repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: flake8
        args: ['--config=setup.cfg']
        additional_dependencies:
          - flake8-bugbear
          - flake8-builtins
          - flake8-commas